---
title: "visualizations_for_schizo"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Prep data and inspect ###

Load data
```{r}
library(pacman)
p_load(tidyverse, patchwork, wesanderson, rcartocolor)
schizo <-  read.csv("sc_schizophrenia.csv")
```

Clean data
```{r}
schizo <- schizo[!is.na(schizo$FirstRating),]
nas <- schizo[is.na(schizo$FirstRating),]

schizo <- schizo %>% mutate(Feedback = OtherRating-FirstRating,
                            Change = SecondRating-FirstRating,
                            Group = ifelse(ID >= 200, "Control", "Sz"))
```
Data inspection
```{r}
summary(schizo)

# How many trials and participants in each group?
schizo %>% group_by(Group) %>% summarize(total_rows = n(),
                                         n_participants = length(unique(ID)))

# How many are excluded from each group?
nas %>% 
  mutate(Group = ifelse(ID >= 200, "Control", "Sz")) %>% 
  group_by(Group) %>% summarize(total_rows = n(),
                                         n_participants = length(unique(ID)))
length(unique(schizo$ID))

```




### Plotting ###
Density plots
```{r}
# Setup
titlesize = 10
ysize = 8

#######################################
## Histograms for relevant variables ##
#######################################

first <- schizo %>% 
  ggplot(aes(FirstRating)) +
    geom_bar(fill="#CC8B3C")+
    scale_x_continuous(breaks = seq(1,8,1))+
    # scale_fill_brewer(palette="Dark2")+
    labs(x = "", y = "Count", title = "Distribution of first rating") +
    theme_bw() +
    theme(plot.title = element_text(size=titlesize),
          text = element_text(size=ysize))

second <- schizo %>% 
  ggplot(aes(SecondRating)) +
    geom_bar(fill="#CC8B3C")+
    scale_x_continuous(breaks = seq(1,8,1))+
    labs(x = "", y = "Count", title = "Distribution of second rating") +
    theme_bw() +
    theme(plot.title = element_text(size=titlesize),
          text = element_text(size=ysize))

feed <- schizo %>% 
  ggplot(aes(Feedback)) +
    geom_bar(fill="#CC8B3C")+
    scale_x_continuous(breaks = seq(-8,8,1))+
    labs(x = "", y = "Count", title = "Distribution of feedback") +
    theme_bw() +
    theme(plot.title = element_text(size=titlesize),
          text = element_text(size=ysize))

other <- schizo %>% 
  ggplot(aes(OtherRating)) +
    geom_bar(fill="#CC8B3C")+
    scale_x_continuous(breaks = seq(-8,8,1))+
    labs(x = "", y = "Count", title = "Distribution of other rating") +
    theme_bw() +
    theme(plot.title = element_text(size=titlesize),
          text = element_text(size=ysize)) 

####################
# Combine and save #
####################

all <- first + second + feed + other
all
ggsave("fig/histograms_all.png", all, width = 10, height = 6)

```


We wanna implement the model sr ~ fr + or --> explore visualizations of that
```{r}
# Setup
text_size = 15

#####################################
## NO FACET, POOL ALL PARTICIPANTS ##
#####################################

# CONTROL 
pool_control <- schizo %>% 
  mutate(OtherRating = as.factor(OtherRating)) %>% 
  filter(Group == "Control") %>% 
  ggplot(aes(FirstRating, SecondRating, color = OtherRating))+
    geom_point(position = "jitter")+
    scale_x_continuous(breaks = seq(1,8,1))+
    theme_bw()+
    labs(x = "First rating", y = "Second rating", title = "Second ratings for control group")+
    scale_color_carto_d(name = "Other rating", palette = "Safe")+
    theme(text = element_text(size=text_size))

# CLINICAL
pool_clinical <- schizo %>% 
  mutate(OtherRating = as.factor(OtherRating)) %>% 
  filter(Group == "Sz") %>% 
  ggplot(aes(FirstRating, SecondRating, color = OtherRating))+
    geom_point(position = "jitter")+
    scale_x_continuous(breaks = seq(1,8,1))+
    theme_bw()+
    labs(x = "First rating", y = "Second rating", title = "Second ratings for clinical group")+
    scale_color_carto_d(name = "Other rating", palette = "Safe")+
    theme(text = element_text(size=text_size))

########################################
## FACET, SHOW INDIVIDUAL DIFFERENCES ##
########################################

# CONTROL
individual_clinical <- schizo %>% 
  mutate(OtherRating = as.factor(OtherRating)) %>% 
  filter(Group == "Sz") %>% 
  ggplot(aes(FirstRating, SecondRating, color = OtherRating))+
    geom_point(position = "jitter")+
    scale_x_continuous(breaks = seq(1,8,1))+
    theme_bw()+
    labs(x = "First rating", y = "Second rating", title = "Second ratings for clinical group")+
    scale_color_carto_d(name = "Other rating", palette = "Safe") +
    facet_wrap(~ID)+
    theme(strip.background = element_blank(),
          panel.spacing = unit(0.05, "lines"),
          text = element_text(size=text_size))

# CLINICAL
individual_control <- schizo %>% 
  mutate(OtherRating = as.factor(OtherRating)) %>% 
  filter(Group == "Control") %>% 
  ggplot(aes(FirstRating, SecondRating, color = OtherRating))+
    geom_point(position = "jitter")+
    scale_x_continuous(breaks = seq(1,8,1))+
    theme_bw()+
    labs(x = "First rating", y = "Second rating", title = "Second ratings for control group")+
    scale_color_carto_d(name = "Other rating", palette = "Safe") +
    facet_wrap(~ID)+
    theme(strip.background = element_blank(),
          panel.spacing = unit(0.05, "lines"),
          text = element_text(size=text_size))

##########
## SAVE ##
##########
ggsave("fig/individual_control.png", individual_control, width = 10, height = 8)
ggsave("fig/individual_clinical.png", individual_clinical, width = 10, height = 8)
ggsave("fig/pool_clinical.png", pool_clinical, width = 10, height = 8)
ggsave("fig/pool_control.png", pool_control, width = 10, height = 8)

```















